# Quick Start Guide

## Supported CompuLab Machines

* `cl-som-imx8`
* `cl-som-imx7`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-rocko -m imx-4.9.88-2.0.0_ga.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b master https://github.com/compulab-yokneam/meta-compulab-bsp.git sources/meta-compulab-bsp

# Set a desire machine
* `cl-som-imx8`
[source,console]
COMPULAB_MACHINE=cl-som-imx8

* `cl-som-imx7`
[source,console]
COMPULAB_MACHINE=cl-som-imx7

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/README?h=rocko-4.9.88-2.0.0_ga#n73[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

This example shows how to build a Wayland image for a supported CompuLab nachine with the Qt5 support.
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-wayland source ./fsl-setup-release.sh -b build-wayland
source ../sources/meta-compulab-bsp/tools/setup-compulab-env
bitbake -k fsl-image-qt5-validation-imx

# Pre-Built Development Image
https://drive.google.com/open?id=1ptJ43j8ExPx7re-Ds0QQrV_o_PQFAJlS[fsl-image-qt5-validation-imx-cl-som-imx8-20181014093522.rootfs.sdcard.bz2]

# Boot from SD-card
* Insert a created SD card into the SD socket `P13` (SB-iMX8 print side).
* Power on the board
* Press and hold `SW5` and `SW6`
* Release `SW5` and then `SW6`

# Wiki Page (TBD)
https://github.com/compulab-yokneam/meta-compulab-bsp/wiki[meta-compulab-bsp wiki]
