
# Important

NOTE: This is an obsolete layer.
Please use this layer `https://github.com/compulab-yokneam/meta-bsp-imx7`

# Quick Start Guide

## Supported CompuLab Machines

* `cl-som-imx7`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-rocko -m imx-4.9.88-2.0.0_ga.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b cl-som-imx7 https://github.com/compulab-yokneam/meta-compulab-bsp.git sources/meta-compulab-bsp

# Set a desire machine
* `cl-som-imx7`
[source,console]
COMPULAB_MACHINE=cl-som-imx7

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/README?h=rocko-4.9.88-2.0.0_ga#n73[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

This example shows how to build an XWayland image for a supported CompuLab machine with the Qt5 support.
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source ./fsl-setup-release.sh -b build-xwayland
source ../sources/meta-compulab-bsp/tools/setup-compulab-env
bitbake -k fsl-image-qt5-validation-imx

# Wiki Page (TBD)
https://github.com/compulab-yokneam/meta-compulab-bsp/wiki[meta-compulab-bsp wiki]
