# Quick Start Guide

## Supported CompuLab Machines

* `ucm-imx8m-mini`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-rocko -m imx-4.9.123-2.3.0-8mm_ga.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b devel-imx8mm https://github.com/compulab-yokneam/meta-compulab-bsp.git sources/meta-compulab-bsp

# Set a desire machine
* `ucm-imx8m-mini`
[source,console]
COMPULAB_MACHINE=ucm-imx8m-mini

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/README?h=rocko-4.9.123-2.3.0_8mm_ga[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

## imx8mm
This example shows how to build a core image for a supported CompuLab machine.
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-wayland source ./fsl-setup-release.sh -b build-wayland
source ../sources/meta-compulab-bsp/meta-bsp-imx8mm/tools/setup-compulab-env
bitbake -k core-image-minimal

# For Developers

## Kernel & U-Boot source how to
https://github.com/compulab-yokneam/Documentation/wiki/iMX8MM-U-Boot-&-Kernel-Source-(4.9.123)

## U-Boot Build how to
https://github.com/compulab-yokneam/Documentation/wiki/iMX8MM-imx-boot-image-build
