SRC_URI_append_cl-som-imx8 = " \
	file://0000-cl-som-imx8-Add-board-support.patch \
	file://0001-cl-som-imx8-Remove-unused-firmware.patch \
	file://0002-cl-som-imx8-Add-usb-support.patch \
	file://0003-cl-som-imx8-Update-Android-support.patch \
	file://0004-cl-som-imx8-Fix-usb-support.patch \
	file://0005-cl-som-imx8-Update-memory-init-code.patch \
	file://0006-cl-som-imx8-pmic-Increase-GPU-power-rail-voltage.patch \
	file://0007-cl-som-imx8-pmic-Increase-DRAM-power-rail-voltage.patch \
	file://cl-som-imx8_defconfig \
"
