#!/bin/bash

### BEGIN INIT INFO
# Provides:		bt-start
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	CompuLab bt-start
### END INIT INFO

# Get the SOM model name
SOM=$(udevadm info -ap /sys/devices/soc0 | awk -F"\"" '(/machine/)&&(split($2,a," ")&&($0=a[2]))')
case "$SOM" in
"UCM-iMX8")
	BT_REG_ON=none
	TTY=ttymxc3
	INIT_SPEED=115200
	SPEED=1500000
	;;
*)
	exit 0;
esac

bluetooth_kill() {
	pkill -9 hciattach
}

bluetooth_stop() {
	if [[ ! -d /sys/class/tty/${TTY}/hci0 ]]
	then
cat << eom
	The Device already stopped.
	Exiting ....
eom
	exit 0
	fi
	bluetooth_kill
}

bluetooth_attach() {
	hciattach -s ${INIT_SPEED} /dev/${TTY} bcm43xx ${SPEED} flow -t 20
}

bluetooth_up() {
	[[ -d /sys/class/tty/${TTY}/hci0 ]] && hciconfig hci0 up
}

bluetooth_status() {
	local mess="connected"
	[[ ! -d /sys/class/tty/${TTY}/hci0 ]] && mess="dis"${mess}
cat << eom
	Device hci0 is ${mess}
eom
}

bluetooth_start() {
	if [[ -d /sys/class/tty/${TTY}/hci0 ]]
	then
cat << eom
	The Device already started.
	Exiting ....
eom
	exit 0
	fi

	bluetooth_attach
	bluetooth_up
}

case "$1" in
start)
	bluetooth_start
	;;
stop)
	bluetooth_stop
	;;
status)
	bluetooth_status
	;;
*)
cat << eom
	Usage: $0 {start|stop|status}
eom
	exit 1
esac

exit 0
