# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "compulab-base"
BBFILE_PATTERN_compulab-base := "^${LAYERDIR}/"
BBFILE_PRIORITY_compulab-base = "9"

LAYERSERIES_COMPAT_compulab-base = "walnascar"

INHERIT += "compulab-base"
ROOTFS_POSTPROCESS_COMMAND += "compulab_basefiles_extra; "
