SRC_URI_append_cl-som-imx8 = " \
	file://0000-cl-som-imx8-Add-CompuLab-device-tree-files.patch \
	file://0001-cl-som-imx8-config-Add-defconfig.patch \
	file://0002-cl-som-imx8-Add-SoM-driver.patch \
	file://0003-sn65dsi83-Add-dsi2lvds-bridge.patch \
	file://0004-ov5640_mipi_v2-gpio-can-sleep.patch \
	file://0005-cl-som-imx8-dtb-Update-Makefile.patch \
	file://0006-cl-som-imx8-Simple-Sound-Support.patch \
	file://0007-cl-som-imx8-dts-Device-tree-refactoring.patch \
	file://0008-cl-som-imx8-defconfig-Update-defconfig.patch \
	file://defconfig \
"
