SRC_URI_append_cl-som-imx8 = " \
	file://0000-cl-som-imx8-Add-CompuLab-device-tree-files.patch \
	file://0001-cl-som-imx8-config-Add-defconfig.patch \
	file://0002-cl-som-imx8-Add-SoM-driver.patch \
	file://0003-sn65dsi83-Add-dsi2lvds-bridge.patch \
	file://0004-ov5640_mipi_v2-gpio-can-sleep.patch \
	file://0005-cl-som-imx8-dtb-Update-Makefile.patch \
	file://0006-cl-som-imx8-Simple-Sound-Support.patch \
	file://0007-cl-som-imx8-dts-Device-tree-refactoring.patch \
	file://0008-cl-som-imx8-defconfig-Update-defconfig.patch \
	file://0009-cl-som-imx8-Fix-SD1_RESET.patch \
	file://0010-cl-som-imx8-defconfig-FRAMEBUFFER_CONSOLE_ROTATION-y.patch \
	file://0011-cl-som-imx8-dts-Add-a-non-edid-dts-file.patch \
	file://0012-imx-hdp-Added-user-defined-video-modes.patch \
	file://0013-cl-som-imx8-sb-Add-hubpwren-regulator.patch \
	file://0014-cl-som-imx8-defconfig-Update-defconfig.patch \
	file://0015-cl-som-imx8-defconfig-Enable-wm8731-with-sdma-as-a-m.patch \
	file://defconfig \
"
