# Quick Start Guide

## Supported CompuLab Machines

* `cl-som-imx8`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-sumo -m imx-4.14.78-1.0.0_ga.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b devel-imx8mq-4.14.78 https://github.com/compulab-yokneam/meta-compulab-bsp.git sources/meta-compulab-bsp

# Set a desire machine
* `cl-som-imx8`
[source,console]
COMPULAB_MACHINE=cl-som-imx8

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/README?h=sumo-4.14.78-1.0.0_ga[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

## imx8mq
This example shows how to build an NXP supported image for the `${COMPULAB_MACHINE}`
[source,console]
MACHINE=${COMPULAB_MACHINE} source sources/meta-compulab-bsp/meta-bsp-imx8mq/tools/setup-imx8mq-env -b build-xwayland
bitbake -k fsl-image-qt5-validation-imx compulab-image-xfce

## Device Trees and available features
* sbc-imx8.dtb -- U-Boot default
* sbc-imx8-bluetooth.dtb -- i8265 BT instead of usb2 hub
* sbc-imx8-lvds-dcss.dtb -- LVDS on dcss
* sbc-imx8-lvds-lcdif.dtb -- LVDS on lcdif
* sbc-imx8-dual.dtb -- LVDS on lcdif and HDMI on dcss

## Set `fdt_file` value
* U-Boot
[source,console]
setenv fdt_file sbc-imx8-bluetooth.dtb

NOTE: U-Boot default environment device is the botloader boot device.

* Linux
[source,console]
fw_setenv fdt_file sbc-imx8-bluetooth.dtb

NOTE: Linux default environment device is eMMC. Refer to `/etc/fw_env.config` for details.


## Pre- built image
* https://drive.google.com/open?id=1fP_EMmb8MRLJ3oShSnmPJy1uT3m_MzAm[Xwayland Qt5 Image]
